version: '3'

services:

  db:
    image: postgres:12
    container_name: flask-db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-secret}
      POSTGRES_DB: ${PG_DB:-postgres}
      PGUSER: ${PG_USER:-postgres}
      PGPASSWORD: ${PG_PASSWORD:-secret}
      PGDATABASE: ${PG_DB:-postgres}
    ports:
      - 127.0.0.1:${LOCAL_PG_PORT:-5432}:5432

  web:
    build: 
      dockerfile: docker/Dockerfile
      context: .
    command: bash ./docker_entrypoint.sh
    container_name: flask-web
    ports:
      - 127.0.0.1:${LOCAL_WEB_PORT:-5000}:5000
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    depends_on:
      - db

volumes:
  db_data:
