version: '3'

services:
  web:
    build: 
      dockerfile: ./docker/python/Dockerfile
      context: .
    container_name: "flask-web"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  
  db:
    image: mysql:8.0
    container_name: "flask-db"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "flask"
      MYSQL_USERNAME: "flask"
      MYSQL_PASSWORD: "flask"
    ports:
      - 3311:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
