"""Create column first_name and last_name in table Users

Revision ID: 301699d8bb26
Revises: 97732e4953c8
Create Date: 2025-03-16 18:07:18.532450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301699d8bb26'
down_revision = '97732e4953c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
